runtime: nodejs12
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  SPOTIFY_CLIENT_ID: "<YOUR_CLIENT_ID>"
  SPOTIFY_CLIENT_SECRET: "<YOUR_CLIENT_SECRET>"
  REDISHOST: '<REDIS_IP>'
  REDISPORT: '6379'
